gestion_assoc/Controllers/ActivityController.cs
using gestion_assoc.Data;
using gestion_assoc.Models.Domain;
using gestion_assoc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace gestion_assoc.Controllers
{
    public class ActivityController : Controller
    {

        private readonly GestionAssocDbContext gestionAssocDbContext;

        public ActivityController(GestionAssocDbContext gestionAssocDbContext)
        {
            this.gestionAssocDbContext = gestionAssocDbContext;
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(AddActivitesViewModel addActivityRequest)
        {
            var activity = new Activites()
            {
                id = Guid.NewGuid(),
                libelle = addActivityRequest.libelle,
                type_activite= addActivityRequest.type_activite,
                date_debut = addActivityRequest.date_debut,
                date_fin = addActivityRequest.date_fin,
                besoin = addActivityRequest.besoin,
                lieu = addActivityRequest.lieu,
            };

            await gestionAssocDbContext.Activites.AddAsync(activity);
            await gestionAssocDbContext.SaveChangesAsync();
            return RedirectToAction("List");

        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var activites = await gestionAssocDbContext.Activites.ToListAsync();
            return View(activites);
        }


        public IActionResult Update()
        {
            return View();
        }

        public IActionResult Show()
        {
            return View();
        }

    }
}

gestion_assoc/Controllers/AssociationController.cs
using gestion_assoc.Data;
using gestion_assoc.Models.Domain;
using gestion_assoc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace gestion_assoc.Controllers
{
    public class AssociationController : Controller
    {

        private readonly GestionAssocDbContext gestionAssocDbContext;

        public AssociationController(GestionAssocDbContext gestionAssocDbContext)
        {
            this.gestionAssocDbContext = gestionAssocDbContext;
        }

        public IActionResult Create()
        {
            return View();
        }



        
        [HttpPost]
        public async Task<IActionResult> Create(AddAssociationViewModel addAssociationRequest)
        {
            var association = new Association()
            {
                Id = Guid.NewGuid(),
                Nom = addAssociationRequest.Nom,
                Tel_1 = addAssociationRequest.Tel_1,
                Tel_2 = addAssociationRequest.Tel_2,
                Email = addAssociationRequest.Email,
                Adresse = addAssociationRequest.Adresse,
            };

            await gestionAssocDbContext.Associations.AddAsync(association);
            await gestionAssocDbContext.SaveChangesAsync();
            return RedirectToAction("List");
            
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var associations = await gestionAssocDbContext.Associations.ToListAsync();
            return View(associations);
        }
         
        public async Task<IActionResult> Read(Guid id)
        {
            var association = await gestionAssocDbContext.Associations.FirstOrDefaultAsync(x => x.Id == id);
            if (association != null)
            {
                var viewModel = new UpdateAssociationViewModel
                {
                    Id = association.Id,
                    Nom = association.Nom,
                    Annee_Creation = association.Annee_Creation,
                    Tel_1 = association.Tel_1,
                    Tel_2 = association.Tel_2,
                    Email= association.Email,
                    Adresse = association.Adresse,
                };

                return await Task.Run(() => View("Read", viewModel));
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Read(UpdateAssociationViewModel model)
        {
            var association = await gestionAssocDbContext.Associations.FindAsync(model.Id);
            if (association != null)
            {
                association.Nom = model.Nom;
                association.Annee_Creation = model.Annee_Creation;
                association.Tel_1 = model.Tel_1;
                association.Tel_2 = model.Tel_2;
                association.Email = model.Email;
                association.Adresse = model.Adresse;

                await gestionAssocDbContext.SaveChangesAsync();
                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateAssociationViewModel model)
        {
            var association = await gestionAssocDbContext.Associations.FindAsync(model.Id);

            if (association != null)
            {
                gestionAssocDbContext.Associations.Remove(association);
                await gestionAssocDbContext.SaveChangesAsync();

                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }
    }
}
    

gestion_assoc/Controllers/FinanceController.cs
using Microsoft.AspNetCore.Mvc;

namespace gestion_assoc.Controllers
{
    public class FinanceController : Controller
    {
        public IActionResult List()
        {
            return View();
        }
    }
}

gestion_assoc/Controllers/MemberController.cs
using gestion_assoc.Data;
using gestion_assoc.Models.Domain;
using gestion_assoc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace gestion_assoc.Controllers
{
    using Data;
    public class MemberController : Controller
    {
        private readonly GestionAssocDbContext gestionAssocDbContext;

        public MemberController(GestionAssocDbContext gestionAssocDbContext)
        {
            this.gestionAssocDbContext = gestionAssocDbContext;
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(AddMembreViewModel addMembreRequest)
        {
            var membre = new Membre()
            {
                id = Guid.NewGuid(),
                nom = addMembreRequest.nom,
                prenom = addMembreRequest.prenom,
                date_naiss= addMembreRequest.date_naiss,
                lieu_naiss = addMembreRequest.lieu_naiss,
               
            };

            await gestionAssocDbContext.membres.AddAsync(membre);
            await gestionAssocDbContext.SaveChangesAsync();
            return RedirectToAction("List");

        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var membres =await gestionAssocDbContext.membres.ToListAsync();
            return View(membres);
        }

        public async Task<IActionResult> Read(Guid id)
        {
            var membre = await gestionAssocDbContext.membres.FirstOrDefaultAsync(x => x.id == id);
            if (membre != null)
            {
                var viewModel = new UpdateMembreViewModel
                {
                    id = membre.id,
                    nom = membre.nom,
                    prenom = membre.prenom,
                    date_naiss = membre.date_naiss,
                    lieu_naiss = membre.lieu_naiss
                    
                };

                return await Task.Run(() => View("Read", viewModel));
            }
            return RedirectToAction("List");
        }


        [HttpPost]
        public async Task<IActionResult> Read(UpdateMembreViewModel model)
        {
            var membre = await gestionAssocDbContext.membres.FindAsync(model.id);
            if (membre != null)
            {
                membre.nom = model.nom;
                membre.prenom = model.prenom;
                membre.date_naiss = model.date_naiss;
                membre.lieu_naiss = model.lieu_naiss;             
                await gestionAssocDbContext.SaveChangesAsync();
                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateMembreViewModel model)
        {
            var membre = await gestionAssocDbContext.membres.FindAsync(model.id);

            if (membre!= null)
            {
                gestionAssocDbContext.membres.Remove(membre);
                await gestionAssocDbContext.SaveChangesAsync();

                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }
    }
}

gestion_assoc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="~/images/">

    <title>@ViewData["Title"]</title>

    <!-- Base Css Files -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Font Icons -->
    <link href="~/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/css/material-design-iconic-font.min.css" rel="stylesheet">

    <!-- animate css -->
    <link href="~/css/animate.css" rel="stylesheet" />

    <!-- Waves-effect -->
    <link href="~/css/waves-effect.css" rel="stylesheet">

    <!-- sweet alerts -->
    <link href="~/assets/sweet-alert/sweet-alert.min.css" rel="stylesheet">

    <!-- Custom Files -->
    <link href="~/css/helper.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="~/js/modernizr.min.js"></script>

</head>



<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- LOGO -->
            <div class="topbar-left">
                <div class="text-center">
                    <a asp-controller="Home" asp-action="Index" class="logo"><i class="md md-terrain"></i> <span>Ges Assoc</span></a>
                </div>
            </div>
            <!-- Button mobile view to collapse sidebar menu -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="">
                        <div class="pull-left">
                            <button class="button-menu-mobile open-left">
                                <i class="fa fa-bars"></i>
                            </button>
                            <span class="clearfix"></span>
                        </div>
                        <form class="navbar-form pull-left" role="search">
                            <div class="form-group">
                                <!-- <input type="text" class="form-control search-bar" placeholder="Type here for search..."> -->
                            </div>
                            <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->

        <div class="left side-menu">
            <div class="sidebar-inner slimscrollleft">
                <div class="user-details">
                    <div class="pull-left">
                        <img src="~/images/users/avatar-1.jpg" alt="" class="thumb-md img-circle">
                    </div>
                    <div class="user-info">
                        <div class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">John Doe <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="profile.html"><i class="md md-face-unlock"></i> Profil<div class="ripple-wrapper"></div></a></li>
                                <li><a href="profile.html"><i class="md md-settings"></i>Paramètres</a></li>
                                <li><a href="javascript:void(0)"><i class="md md-settings-power"></i> Déconnexion</a></li>
                            </ul>
                        </div>

                        <p class="text-muted m-0">Administrateur</p>
                    </div>
                </div>
                <!--- Divider -->
                <div id="sidebar-menu">
                    <ul>
                        <li>
                            <a asp-controller="Home" asp-action="Index" class="waves-effect"><i class="md md-home"></i><span> Acceuil </span></a>
                        </li>

                        <li class="has_sub">
                            <a href="#" class="waves-effect"><i class=" md-store"></i><span> Associations </span><span class="pull-right"><i class="md md-add"></i></span></a>
                            <ul class="list-unstyled">
                                <li><a asp-controller="Association" asp-action="Create">Ajouter une association</a></li>
                                <li><a asp-controller="Association" asp-action="List">Liste des associations</a></li>
                            </ul>
                        </li>

                        <!-- <li>
                            <a href="calendar.html" class="waves-effect"><i class="md md-event"></i><span> Calendar </span></a>
                        </li> -->

                        <li class="has_sub">
                            <a href="#" class="waves-effect"><i class="md-people"></i> <span> Membres </span> <span class="pull-right"><i class="md md-add"></i></span></a>
                            <ul class="list-unstyled">
                                <li><a asp-controller="Member" asp-action="Create">Ajouter un membre</a></li>
                                <li><a asp-controller="Member" asp-action="List">Liste des membres</a></li>
                            </ul>
                        </li>

                        <li class="has_sub">
                            <a href="#" class="waves-effect"><i class="md-star-half"></i><span> Activités </span><span class="pull-right"><i class="md md-add"></i></span></a>
                            <ul class="list-unstyled">
                                <li><a asp-controller="Activity" asp-action="Create">Ajouter une activité</a></li>
                                <li><a asp-controller="Activity" asp-action="List">Liste des activités</a></li>
                            </ul>
                        </li>

                        <li class="has_sub">
                            <a href="#" class="waves-effect"><i class="md-trending-up"></i> <span> Finance </span> <span class="pull-right"><i class="md md-add"></i></span></a>
                            <ul class="list-unstyled">
                                <li><a asp-controller="Finance" asp-action="List">Liste des cotisations</a></li>
                                <li><a href="ion-icons.html">Vue globale</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">

            <div class="content">
                @RenderBody()
            </div>
            <footer class="footer text-right">
                2022 © Shado.
            </footer>

        </div>
        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->

    </div>
    <!-- END wrapper -->



    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/assets/chat/moment-2.2.1.js"></script>
    <script src="~/assets/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script src="~/assets/jquery-detectmobile/detect.js"></script>
    <script src="~/assets/fastclick/fastclick.js"></script>
    <script src="~/assets/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="~/assets/jquery-blockui/jquery.blockUI.js"></script>

    <!-- sweet alerts -->
    <script src="~/assets/sweet-alert/sweet-alert.min.js"></script>
    <script src="~/assets/sweet-alert/sweet-alert.init.js"></script>

    <!-- flot Chart -->
    <script src="~/assets/flot-chart/jquery.flot.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.time.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.tooltip.min.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.resize.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.pie.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.selection.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.stack.js"></script>
    <script src="~/assets/flot-chart/jquery.flot.crosshair.js"></script>

    <!-- Counter-up -->
    <script src="~/assets/counterup/waypoints.min.js" type="text/javascript"></script>
    <script src="~/assets/counterup/jquery.counterup.min.js" type="text/javascript"></script>

    <!-- CUSTOM JS -->
    <script src="~/js/jquery.app.js"></script>

    <!-- Dashboard -->
    <script src="~/js/jquery.dashboard.js"></script>

    <!-- Chat -->
    <script src="~/js/jquery.chat.js"></script>

    <!-- Todo -->
    <script src="~/js/jquery.todo.js"></script>

    <script type="text/javascript">
        /* ==============================================
        Counter Up
        =============================================== */
        jQuery(document).ready(function($) {
            $('.counter').counterUp({
                delay: 100,
                time: 1200
            });
        });
    </script>

</body>
</html>